export const ESC = '\x1B'
export const CSI = ESC + '['
export const OSC = ESC + ']'
export const DCS = ESC + 'P'

export const BEL = '\x07'
export const BS = '\x08'
export const HT = '\x09'
export const LF = '\x0A'
export const VT = '\x0B'
export const FF = '\x0C'
export const NP = '\x0C'
export const CR = '\x0D'
export const DEL = '\x7F'
export const ST = '\x1b \x5c'
