export default {
  percent: 0,
  filledWidth: 0,
  emptyWidth: 0,
  elapsed: 0,
  rate: 0,
  completed: 0,
  total: 1,
  color: 'whiteBright',
  processMessage: '',
  processMessageColor: 'gray',
  type: 'dots',
  unitName: 'unit',
  bar: '█',
  empty: '░',
}
